version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:16.20 # Node.js environment for building and testing

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  dockerize-and-push:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t deepdhiman/nodejs-app:latest .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image
          command: docker push deepdhiman/nodejs-app:latest

workflows:
  build-test-and-push:
    jobs:
      - build
      - dockerize-and-push:
          requires:
            - build
